# ---------------------------
# API ROUTES
# ---------------------------

# AUTHENTICATE
api_authenticate:
  path: /auth
  controller: App\Api\Authenticate::auth
  methods: POST

# USERS
api_users_get:
  path: /users
  controller: App\Api\User::getAllUsers
  methods: GET

api_user_id_get:
  path: /user
  controller: App\Api\User::getUserById
  methods: GET

api_users_add:
  path: /user/add
  controller: App\Api\User::add
  methods: POST

api_users_update:
  path: /user/update
  controller: App\Api\User::update
  methods: POST

api_users_upload:
  path: /user/upload
  controller: App\Api\User::upload
  methods: POST

# CENTERS
api_centers_get:
  path: /centers
  controller: App\Api\Center::getAllCenters
  methods: GET

  # APPLICATION 

api_app_role_get:
  path: /roleapp
  controller: App\Api\Application::getRolesAppsUser
  methods: GET