# ---------------------------
# API ROUTES
# ---------------------------

# AUTHENTICATE
api_authenticate:
  path: /auth
  controller: App\Api\Authenticate::auth
  methods: POST

# USERS
api_users_get:
  path: /users
  controller: App\Api\User::getAllUsers
  methods: GET

api_users_add:
  path: /user/add
  controller: App\Api\User::add
  methods: POST

api_users_upload:
  path: /user/upload
  controller: App\Api\User::upload
  methods: POST